### ISSUE TITLE
[Bug]: Stable packages has "Nightly" package referances

### ISSUE THREAD

**Issue by W4TR1X** [Krypton-Suite/Extended-Toolkit#347] opened 2022-08-17 10:51 UTC
**Describe the bug**
Krypton.Toolkit.Suite.Extended.* Stable packages has nightly package referances

**Screenshots**
![image](https://user-images.githubusercontent.com/30633382/185100868-4a96a611-b11b-49d0-a106-3bbaf9ad7e33.png)
![image](https://user-images.githubusercontent.com/30633382/185101113-ce15a213-a204-45be-a86f-541f146cd7dd.png)

**Comment by Wagnerp** [comment] 2022-08-20 16:11
Duplicate of https://github.com/Krypton-Suite/Extended-Toolkit/issues/324 - closing

**Closed by Wagnerp** 2022-08-20 16:11 UTC
Labels: bug, duplicate
